pipeline{
    agent any
    triggers {
        GenericTrigger(
            genericVariables: [[key: 'ref', value: '$.ref']],
            token: 'abc123',
            causeString: 'Triggered on $ref',
            regexpFilterExpression: '',
            regexpFilterText: '',
            printContributedVariables: true,
            printPostContent: true
        )
    }
    stages{
        stage("Clone"){
            steps{
                git branch: 'main', url: "https://github.com/lvan92/dc11_dot_vanle_terraform", credentialsId: 'ee7270cf-02cf-41aa-b1e0-bb4dd14636bc'
            }
        }
        stage('Terraform Init') {
            steps {
                withAWS(credentials: '97bdd615-545a-4323-aec6-63db7926f133', region:'us-east-1') {
                    // sh 'terraform init -reconfigure'
                    echo 'Test step'
                    // sh 'terraform apply --auto-approve'
                }
            }
        }
    }
    post{
        success{
           echo "Success"
        }

        failure{
            echo "Failure"
        }
    }
}