pipeline{
    agent any
    stages{
        stage("Clone"){
            steps{
                git branch: 'main', url: "https://github.com/lvan92/dc11_dot_vanle_terraform", credentialsId: 'ee7270cf-02cf-41aa-b1e0-bb4dd14636bc'
            }
        }
        stage('Terraform Init') {
            steps {
                sh 'terraform init'
                echo '[Debug] Running terraform init successfully~'
            }
        }
        stage('Terraform Plan') {
            steps {
                sh 'terraform plan'
                echo '[Debug] Running terraform plan successfully~'
            }
        }
        stage('Terraform apply') {
            steps {
                sh 'terraform apply --auto-approve'
            }
        }
    }
    post{
        success{
           echo "Success"
        }

        failure{
            echo "Failure"
        }
    }
}